### ISSUE TITLE
item scanner hangs indefinitely

### ISSUE THREAD

**Issue by LyricDev** [LyricDev/Research#15]
It is possible for a spider to get a page and hold it forever. Not sure what causes this but it results in swarm not stopping. When originally noticed a single page was causing the hang. See comment for html

If hangup cannot be found consider milder stopping criteria (e.g. incomplete pages < 2);

**Comment by LyricDev** [comment]
html uploaded as pdf
[hung page.pdf](https://github.com/LyricDev/Research/files/1315592/hung.page.pdf)

**Comment by LyricDev** [comment]
another fix option is to detect this state and throw an emailable exception - at least user will know to intervene

**Comment by LyricDev** [comment]
suspect this is due to spider death on runtime exception leaving db unprocessed - fixing all known exceptions should sort this

**Comment by LyricDev** [comment]
another exception in item scanner caused this again after - consider changing stopping criteria. see bellow for exception log

**Comment by LyricDev** [comment]
java.lang.RuntimeException: Exception whilst processing page idpages: 14623 url: http://www.amazon.co.uk/s/ref=sr_pg_2/257-2892503-7241859?fst=as%3Aoff&rh=n%3A65801031%2Cp_76%3A419159031%2Cp_36%3A3000-100000%2Cn%3A%2166280031%2Cn%3A2826465031%2Cn%3A2826470031%2Cn%3A2826489031&page=2&bbn=2826470031&ie=UTF8&qid=1505929517 longTitle: Health & Personal Care > Diet & Nutrition > Slimming Aids & Weight Loss > Detox & Cleanse lastRank: 24 completed: false spiderAllocated: NULL parent: NULL nPages: 2 
For item iditems: 0 ASIN: B002RSMUUG imageUrl:  title: NULL url: NULL primeAvailable: false limitedStockInfo: 1000 rating: 2.5 completed: false price: NULL strikePrice: NULL pageID: NULL itemRank: 0 
Item ignored
	at chunky.itemscanner.CItemSpider.ProcessPageJsoup(CItemSpider.java:267)
	at chunky.itemscanner.CItemSpider.OnSpiderStep(CItemSpider.java:55)
	at chunky.common.CBaseSpider.OnStep(CBaseSpider.java:58)
	at chunky.common.CStatefulThread.run(CStatefulThread.java:200)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at chunky.itemscanner.CItemSpider.ProcessPageJsoup(CItemSpider.java:244)
	... 3 more

**Comment by LyricDev** [comment]
latest issue fixed so no exceptions are thrown. This was being caused by a totally blank item on the page - such items are now ignored and flagged as warnings rather than throwing an exception
